name: Dotnet build CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Build WeatherService.Data
      run: |
        cd WeatherService.Data
        dotnet build --configuration Release

    - name: Build WeatherService.Web
      run: |
        cd WeatherService.Web
        dotnet build --configuration Release